### ISSUE TITLE
EMAS - aktualizacja i poszerzenie dokumentacji

### ISSUE THREAD

**Issue by 0xtrzy** [jakubfi/emas#2]
Jak napisać swój pierwszy program?
Coś na początek. Powiedzmy jakas pętla i coś co wypisuje dane. Niestety nie mam jak wysłac wiadomość bezpośrednio.

**Comment by Mati365** [comment]
Dołączam się do pytania. Brakuje opisu składni asemblera

**Comment by jakubfi** [comment]
Na dobry początek:

Opis assemblera EMAS jest [tutaj](https://mera400.pl/EMAS). Niektóre elementy składni mogły w międzyczasie ulec zmianie bez aktualizacji dokumentacji, TBD. Lista rozkazów procesora MERY-400 jest [tutaj](https://mera400.pl/Lista_rozkaz%C3%B3w). Odrobinę inspiracji na temat tego, jak używać emasa można zaczerpnąć [stąd](https://github.com/jakubfi/em400/tree/master/tests/functional/addr)

TODO:
- przejrzeć, zaktualizować i uzupełnić dokumentację emas-a
- udokumentować standardowe nagłówki
- dostarczyć przykładowe programy

**Comment by fab1an2** [comment]
To ja (może jako głos społeczności) prosze o jeden przykład.
Opisać maksymalnie dokładnie program porównywalny z BrainFuck (wejście z klawiatury i wyjście) operacje dodawania i odejmowania, petla (lub skok warunkowy).

Dobrze było by też dać choć wzmiankę jak zapisywać polskie litery. Czy klawiatura mery miała inne klawisze (pamiętam kłódka, klawisz obecnie nieobecny w żadnej klawiaturze)

Idealnie gdyby to pokazac na emulatorze, jak skompilować, jak uruchomić itp. Ludzie mają chęć, może napiszą jakieś parsery, może llvm, ale od czegoś trzeba zacząć.

P.S. A i czy liczby integer  ?ZM i ?MZ sa takie same? można je dowolnie mieszac?

**Comment by jakubfi** [comment]
Kolejność flag w zapisie z "?" nie ma znaczenia:
```
$ emas -O debug
.word ?MZ, ?ZM
@ 0x0000 : 0xc000  /  110 000 0 000 000 000  /  49152
@ 0x0001 : 0xc000  /  110 000 0 000 000 000  /  49152
```

**Comment by 0xtrzy** [comment]
Widzę, że wątek się rozrósł, ale nadal nie bardzo wiem jak napisac swój pierwszy program. Ani jak go wczytać i uruchomić. Czy taka opcja z -O debug pozwala sprawdzić wynik programu? Powiedzmy, że wynikiem jest jakis napis. Nie trzeba by było uruchamiać emulatora. A ja nawet nie wiem jak wczytać plik skompilowany ani jak go wytworzyć.

**Comment by jakubfi** [comment]
> Ani jak go wczytać i uruchomić.

Najprostszy sposób na załadowanie programu do emulatora to uruchomić go z opcją -p, podając jako argument nazwę pliku ze zassemblowanym, binarnym programem. Uruchomić go można wpisując polecenie "start" w oknie emulatora.

> Czy taka opcja z -O debug pozwala sprawdzić wynik programu?

Nie, pozwala tylko zobaczyć jak binarny program wygląda po zassemblowaniu

**Comment by jakubfi** [comment]
Dokumentacja EMAS-a została zaktualizowana. Przykładowe programy pokazujące realizację pętli i wyświetlanie łańcucha zostały dodane do repozytorium: https://github.com/jakubfi/emas/tree/master/examples

**Comment by Mati365** [comment]
Wydaje mi się, że tego typu informacje powinny być od razu w README.md. Podziwiam Twoją pracę z wskrzeszeniem tego klasyka ale bez opracowania tego w przystępnej formie tak by byle laik mógł odpalić sobie swój własny program wszystkie Twoje starania idą na marne.

**Comment by jakubfi** [comment]
Gorąco zachęcam zainteresowanych do opracowania tego w przystępnej formie! :-)
To niestety jest jedynie repozytorium kodu źródłowego i o ile dokumentacja narzędzia jest jak najbardziej elementem projektu i jej aktualizacja mieści się w zakresie naprawy błędów oprogramowania, o tyle tutoriale zdecydowanie poza ten zakres wykraczają.

**Comment by 0xtrzy** [comment]
Zaproponowałem by dodać przykłady. I jak je uruchomić. Nadal nie wiem jak napisac przykład. 
Myślę, że jeśli nie napiszesz sam lub ktoś z grupy jakiegoś przykładu nikt inny nie napisze żadnej instrukcji ani nie poprawi dokumentacji. 

Wydaje mi się, że zamykając to wydanie zamykasz się na nowych użytkowników i programistów. Nie mam złudzeń.

**Comment by jakubfi** [comment]
Uruchomienie przykładowych programów z repozytorium emas-a zostało opisane [tutaj](https://mera400.pl/EM400_-_uruchamianie_program%C3%B3w).
