### ISSUE TITLE
testy są zależne od emulatora

### ISSUE THREAD

**Issue by wir19** [jakubfi/emas#3]
W katalogu testowym jest na stałe wpisana informacja gdzie jest emulator co nie zawsze jest prawdziwe.

Dotyczylo by to też katalogu z [...]/em400/tests/include

Może dodać dytektywę **make test**

**Comment by wir19** [comment]
Czy napisałem coś nieprawdziwego? czy testty nie sa wazne?
czemu zamykasz ten wątek?
Hallo, tu ziemia co robisz?

**Comment by jakubfi** [comment]
> Czy napisałem coś nieprawdziwego? czy testty nie sa wazne?

Testy są jak najbardziej ważne. 

> czemu zamykasz ten wątek?

Wskazany błąd został naprawiony: test runner został zaktualizowany w 4894f038a361798924d44318e08bd1d1b421e2ff i wymaga teraz podania katalogu z testami em400. Zmiana formy uruchomienia testów nie jest planowana, jako że jest to funkcjonalność wewnętrzna (nie dla użytkownika) i w obecnej postaci wystarczająca.

**Comment by wir19** [comment]
moze warto napisac ze cos poprawiles i dopiero wtedy zamknac watek. inaczej nie wiadomo o co chodzi

**Comment by jakubfi** [comment]
> moze warto napisac ze cos poprawiles i dopiero wtedy zamknac watek. inaczej nie wiadomo o co chodzi

Problem został zamknięty z informacją "jakubfi closed this in 4894f03 5 days ago" - proszę czytać uważniej.

**Comment by wir19** [comment]
nadal uważam, że jest to niejednoznaczne. pisz po prostu że coś zostało naprawione lub nie. to że zostało zamkniete w takiej wersji nic nie oznacza
