### ISSUE TITLE
Jak uruchomić przykłady, jak dodać testy i benchmark

### ISSUE THREAD

**Issue by wir19** [jakubfi/emas#4]
Wydaje się, że dobrym pomysłem było by umożliwienie przetestowania konkretnych programów. 

to co jest w 'exemple' jak to uruchomić? jak sprawdzić czy jest to poprawne binarnie i czy kompilacja powoduje odpowiedni kod?

Jak zrobic benchmark, aby wiedzieć czy dane rozwiązanie jest szybsze czy nie?

Zrobiłem jak proponowałeś 
`./em400 -c ./em400.ini -p ./loops.out`
i nic się nie dzieje. Jak zobaczyć co liczy, czy liczy, jak wyświetlić wynik?

Jakis konkretny przykład?

**Comment by jakubfi** [comment]
> Wydaje się, że dobrym pomysłem było by umożliwienie przetestowania konkretnych programów.

Testowanie programów nie należy do zadań EMAS-a, który jest tylko assemblerem. Testowanie, zwłaszcza konkretnych programów, wymaga innych narzędzi.

> to co jest w 'exemple' jak to uruchomić?

Katalog 'examples' zawiera przykładowe programy napisane z użyciem składni i mnemoników asemblera EMAS. Ich celem jest wyłącznie zaprezentowanie składni. Uruchomić można je w emulatorze EM400.

>  jak sprawdzić czy jest to poprawne binarnie i czy kompilacja powoduje odpowiedni kod?

j.w.: to nie należy do zadań EMAS-a, który jest tylko assemblerem.

> Jak zrobic benchmark, aby wiedzieć czy dane rozwiązanie jest szybsze czy nie?

j.w.: to nie należy do zadań EMAS-a, który jest tylko assemblerem.

> Zrobiłem jak proponowałeś `./em400 -c ./em400.ini -p ./loops.out` i nic się nie dzieje. Jak zobaczyć co liczy, czy liczy, jak wyświetlić wynik?

Odsyłam do opisu poleceń debuggera emulatora EM400: https://mera400.pl/Debugger_EM400
W przypadku programu loops wynik nie jest wyświetlany, można go jedynie podejrzeć w rejestrach procesora.

**Comment by wir19** [comment]
ale w sekcji em400 tez nie odpowiedziales jak to uruchomic

ponawiam pytanie jak uruchomic i sprawdzic testowe programy. od czego sa zalezne (jak sprawdzic) i jak uzyskac wynik. nie zamykaj pospiesznie watku skoro nie ma odpowiedzi

**Comment by wir19** [comment]
Hallo
napisz jak uruchomic przykłady. W sumie nie pamiętam byś odpowiedział na jakiekolwiek konkretne pytanie.
podał przykład czegokolwiek. odsyłasz do dokumentacji z której często nic nie wynika bo nie ma tam odpowiedzi na pytanie. 
Wysil sie i pokaż konkretnie jak cos zrobić

**Comment by jakubfi** [comment]
Uruchomienie przykładowych programów z repozytorium emas-a zostało opisane [tutaj](https://mera400.pl/EM400_-_uruchamianie_program%C3%B3w).
